name: mkdocs
channels:
  - defaults
dependencies:
  - python=3.10  
  - pip
  - pip:
      - mkdocs==1.6.1
      - mkdocs-material==9.7.7
      - mkdocs-glightbox
      - mkdocs-statistics-plugin
      - mkdocs-git-revision-date-localized-plugin
      - mkdocs-callouts
      - mkdocs-minify-plugin
      - mkdocs-video
      - mkdocs-blogging-plugin
